### ISSUE TITLE
username error on chat page

### ISSUE THREAD

**Issue by b1oki** [alexandersobyanin/alexandersobyanin.ru#46]
**Describe the bug**

```
TypeError: Cannot read property 'username' of undefined
  at n.value (components/Messages/messageItem.jsx:41:35)
  at Fa (/static/js/2.067a6fa9.chunk.js:1:208816)
  at Ma (/static/js/2.067a6fa9.chunk.js:1:208609)
  at ys (/static/js/2.067a6fa9.chunk.js:1:244520)
  at cu (/static/js/2.067a6fa9.chunk.js:1:235735)
...
(25 additional frame(s) were not displayed)
```

**To Reproduce**
1. Go to https://alexandersobyanin.ru/chat/

**Expected behavior**
Chat page

**Comment by b1oki** [comment]
prepare

**Comment by b1oki** [comment]
After fix new bug

```
Uncaught (in promise) TypeError: Cannot read property 'roles' of null
    at firebase.js:77
```
